name: workout_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  hive: ^2.2.3  # storing user input data by hive
  hive_flutter: ^1.1.0  # storing user input data by hive
  flutter_heatmap_calendar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
